services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  web:
    build: .
    env_file:
      - .env
    command: python website/manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db

volumes:
  postgres_data:
