# Generated by Django 5.0.6 on 2024-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='products', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(default='https://t.me/Nodirbyte', verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/nodirbyte', null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/nodirbyte', null=True, verbose_name='Instagram')),
                ('wechat', models.URLField(blank=True, default='https://www.wechat.com/nodirbyte', null=True, verbose_name='WeChat')),
                ('whatsapp', models.URLField(blank=True, default='https://www.whatsapp.com/nodirbyte', null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='nodirbyte@gmail.com', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+998 99 785 48 02', max_length=15, null=True, verbose_name='Phone')),
                ('location', models.CharField(blank=True, default='Tashkent, Uzbekistan', max_length=255, null=True, verbose_name='Location')),
                ('location_map', models.URLField(blank=True, default='https://goo.gl/maps/1JZzZQ1Zz1Z1Zz1Z1', null=True, verbose_name='Location Map')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('products', models.ManyToManyField(related_name='product_types', to='app.product')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
    ]
